# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test StoreApi")

api.instance <- StoreApi$new()

test_that("DeleteOrder", {
  # tests for DeleteOrder
  # base path: http://api.pubi.org/v2
  # Delete purchase order by ID
  # For valid response try integer IDs with positive integer value. Negative or non-integer values will generate API errors
  # @param order.id integer ID of the order that needs to be deleted
  # @return [Void]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetInventory", {
  # tests for GetInventory
  # base path: http://api.pubi.org/v2
  # Returns pet inventories by status
  # Returns a map of status codes to quantities
  # @return [map(integer)]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("GetOrderById", {
  # tests for GetOrderById
  # base path: http://api.pubi.org/v2
  # Find purchase order by ID
  # For valid response try integer IDs with value &gt;&#x3D; 1 and &lt;&#x3D; 10. Other values will generated exceptions
  # @param order.id integer ID of pet that needs to be fetched
  # @return [Order]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("PlaceOrder", {
  # tests for PlaceOrder
  # base path: http://api.pubi.org/v2
  # Place an order for a pet
  # @param body Order order placed for purchasing the pet
  # @return [Order]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

